name: first workflow
on:
  push:
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - run: |
          date
          pwd    
  third-job:
    needs: second-job
    runs-on: ubuntu-latest
    steps:
    - name: Multi-line bash
      run: |
        echo "I am"
        echo "a multi-line"
        echo "script.