name: second workflow
on:
  #push:
  workflow_dispatch:
  pull_request:
    branches:
      - main
<<<<<<< HEAD
  # schedule:
  #   - cron: '0/1 0 * * *'      
=======
  schedule:
    - cron: '0/5 * * * *'      
>>>>>>> c48dda37b48e37821bbf7d4d11bfa5dac396f1ee
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show Event Trigger
        run: |
          echo "Triggered by event name: ${{ github.event_name }}"
          echo "Triggered by actor: ${{ github.actor }}"
          echo "Ref/Branch: ${{ github.ref }}"


